### ISSUE TITLE
Kan vi autofylla med username i DisplayName

### ISSUE THREAD

**Issue by kumorig** [KhaledZra/DustBustersUnited#143]
Helt i mån av tid och lust, men kan vi autofylla med användarens username? 
![image](https://github.com/KhaledZra/DustBustersUnited/assets/5523938/b40928a7-f4f6-42d1-a128-5f3ad7c0d7ac)

färre knapptryck åt folket!

**Comment by 85johsve** [comment]
Den autofyller men för att knappen ska aktiveras måste man fortfarande göra en ändring i textfälltet. Inte så snyggt.
