### ISSUE TITLE
Client - householdInfoScreen lists households profiles instead of users profiles

### ISSUE THREAD

**Issue by 85johsve** [KhaledZra/DustBustersUnited#145]

**Comment by kumorig** [comment]
@85johsve 

Stämmer det verkligen? är inte det skärmen man kommer till från menyn?
![image](https://github.com/KhaledZra/DustBustersUnited/assets/5523938/ce0ebb4e-57eb-4d63-9bec-2f2f65f9d950)

![image](https://github.com/KhaledZra/DustBustersUnited/assets/5523938/0a7f20fa-c76e-4654-b738-49b115d36919)

**Comment by 85johsve** [comment]
Det stämmer, det är den skärmen. Om du har fler profiler på samma user så listas dom där.

**Comment by 85johsve** [comment]
fixat va
